# Generated by Django 5.2.12 on 2026-04-02 22:02

import apps.accounts.models
from django.db import migrations, models


def backfill_user_emails(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for u in User.objects.all():
        email = (getattr(u, "email", "") or "").strip()
        if email:
            continue
        uname = (u.username or "").strip()
        if "@" in uname:
            u.email = uname
        else:
            u.email = f"user-{u.pk}@migrate.illeto.local"
        u.save(update_fields=["email"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.RunPython(backfill_user_emails, noop_reverse),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
