# Generated by Django 5.2.12 on 2026-04-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_email_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Étudiant / grand public'), ('PROFESSIONAL', 'Professionnel'), ('INSTITUTION', 'Institution')], db_index=True, default='STUDENT', max_length=32),
        ),
    ]
