# Generated by Django 5.2.12 on 2026-04-03 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_type'),
        ('geo_data', '0004_point_interet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorited_by_users', to='geo_data.commune', verbose_name='commune favorite (décideur)'),
        ),
        migrations.CreateModel(
            name='ExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(default='unknown', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'journal d’export',
                'verbose_name_plural': 'journaux d’export',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShapefileLibraryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('territory_type', models.CharField(max_length=16)),
                ('territory_id', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapefile_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'export Shapefile',
                'verbose_name_plural': 'exports Shapefile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommuneSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='geo_data.commune')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commune_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_co_user_id_eebc16_idx')],
            },
        ),
    ]
