version: '3.8'

services:
  db:
    image: postgis/postgis:14-3.2
    container_name: ileto_db_container
    restart: always
    environment:
      - POSTGRES_DB=illeto_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=motdepasse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: