# Generated by Django 5.2.12 on 2026-04-02 22:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'département',
                'verbose_name_plural': 'départements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='geo_data.departement', verbose_name='département')),
            ],
            options={
                'verbose_name': 'commune',
                'verbose_name_plural': 'communes',
                'ordering': ['name'],
            },
        ),
    ]
