# Generated by Django 5.2.12 on 2026-04-03 07:44

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0002_commune_is_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='is_placeholder',
            field=models.BooleanField(default=False, help_text='True = seed dev uniquement ; import officiel → False. API liste/GeoJSON masque les True si ILLETO_GEO_INCLUDE_PLACEHOLDER_COMMUNES est False.', verbose_name='donnée factice'),
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('osm_id', models.CharField(blank=True, help_text='Ex. relation/123456 — pour réimport idempotent.', max_length=128, null=True, unique=True, verbose_name='identifiant OSM')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='geo_data.commune', verbose_name='commune')),
            ],
            options={
                'verbose_name': 'quartier',
                'verbose_name_plural': 'quartiers',
                'ordering': ['name'],
                'unique_together': {('commune', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('osm_id', models.CharField(blank=True, help_text='Ex. relation/123456 — pour réimport idempotent.', max_length=128, null=True, unique=True, verbose_name='identifiant OSM')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='geo_data.commune', verbose_name='commune')),
            ],
            options={
                'verbose_name': 'zone (arrondissement)',
                'verbose_name_plural': 'zones (arrondissements)',
                'ordering': ['name'],
                'unique_together': {('commune', 'name')},
            },
        ),
    ]
