# Generated by Django 5.2.12 on 2026-04-03 08:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0003_zone_quartier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('category', models.CharField(choices=[('health', 'Santé'), ('market', 'Marché'), ('transport', 'Transport'), ('education', 'Éducation'), ('culture', 'Culture'), ('admin', 'Administration'), ('other', 'Autre')], default='other', max_length=32, verbose_name='catégorie')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('external_id', models.CharField(blank=True, help_text='Clé idempotente (ex. OSM node id) pour réimport.', max_length=128, null=True, unique=True, verbose_name='identifiant externe')),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_interet', to='geo_data.commune', verbose_name='commune')),
                ('quartier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_interet', to='geo_data.quartier', verbose_name='quartier')),
            ],
            options={
                'verbose_name': "point d'intérêt",
                'verbose_name_plural': "points d'intérêt",
                'ordering': ['name'],
            },
        ),
    ]
